### ISSUE TITLE
Failure when parsing anonymous parameters

### ISSUE THREAD

**Issue by Nemo157** [dtolnay/syn#746] opened 2020-01-10 12:54 UTC
This snippet of code from `dtoa` fails parsing with `syn` 1.0.13:

```rust
pub trait Floating {
    fn write<W: io::Write>(self, W) -> io::Result<usize>;
}
```

Giving the error ``Error("expected `:`")``. This is valid code _in edition 2015_, edition 2018 has made it a hard error, here's [a playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=e8e7d13fae9f41d52858197e42c9d06d) which compiles successfully with the code, and shows the error from `syn`.

I have also locally tested defining an identity `proc-macro-attribute` which attempts to parse whatever it's applied to as an `syn::Item`. That also fails with the same error message.

**Comment by mystor** [comment] 2020-01-10 18:14
See-also #733. Recent versions of `syn` don't handle parsing edition 2015-only code.
Version 0.13.0 is also out-of-date, the latest version is 1.0.13.

**Comment by Nemo157** [comment] 2020-01-10 18:35
Whoops, I meant 1.0.13.

If `syn` isn’t planning to support edition 2015 code it would be good to note that somewhere. I did take a quick look through the docs to try and figure out if it was a purposeful omission.

**Comment by dtolnay** [comment] 2022-12-01 01:48
Closing as a duplicate of #733. I don't plan to change how this is parsed.

Regarding documentation, I am skeptical that this would come up often enough to be worth dedicating documentation to.

**Closed by dtolnay** 2022-12-01 01:48 UTC
