### ISSUE TITLE
If proc_macro2 parse line comment?

### ISSUE THREAD

**Issue by ice-tong** [dtolnay/syn#1045] opened 2021-08-14 05:39 UTC
Hi, thank you for your nice work!
I'm using syn to compute LOC (line of code) metrics of Rust code.

I have a problem when I try to count comment lines. I find that syn does not parse line comment into TokenStream.
A examples:
```Rust
let fn_body: syn::ItemFn = parse_quote! {
            fn test_cc() {
                //  line comments here
                let i = 1; 
            }
        };
println!("{:#?}", fn_body);
```
Do you have any solution or suggestion about that?

**Comment by dtolnay** [comment] 2021-09-02 06:30
Closing as a duplicate of #946.

**Closed by dtolnay** 2021-09-02 06:30 UTC
