### ISSUE TITLE
Parse_Str does not return a correct error

### ISSUE THREAD

**Issue by Bleachfuel** [dtolnay/syn#1780] opened 2024-11-09 14:28 UTC
why does `parse_str` not return the span at which it failed? Or does it do that and am I missing something, because I'm having trouble highlighting the spans at which parsing fails.

```rust 
        if let Some(lit) = literal {
            syn::parse_str::<syn::WherePredicate>(&lit.value())
            .map(Some)
            .map_err(|err| {
                syn::Error::new_spanned(lit, err)
            })
        } else {
            Ok(None)
        }
```

**Comment by dtolnay** [comment] 2024-12-15 18:36
For parsing tokens inside a LitStr, this is a duplicate of https://github.com/dtolnay/syn/issues/621.

**Closed by dtolnay** 2024-12-15 18:36 UTC
