### ISSUE TITLE
syn accepts incomplete strings as valid syntax

### ISSUE THREAD

**Issue by canndrew** [dtolnay/syn#584] opened 2019-02-25 12:29 UTC
For some reason this string parses just fine as a `syn::Expr`

    Foo::Bar { elem

Even without a closing parenthesis. Seems like this should probably return an `Err`.

**Comment by dtolnay** [comment] 2019-02-25 19:07
Closing because I was not able to reproduce this. Let me know if you were looking at something different.

#### Cargo.toml

```toml
[package]
name = "repro"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
syn = { version = "0.15", features = ["full"] }
```

#### src/main.rs

```rust
use syn::Expr;

fn main() {
    let code = "Foo::Bar { elem";
    let is_err = syn::parse_str::<Expr>(code).is_err();
    println!("{}", is_err);
    assert!(is_err);
}
```

```console
true
```

**Closed by dtolnay** 2019-02-25 19:07 UTC

**Comment by dtolnay** [comment] 2019-02-25 19:26
I think what you may be seeing is automatic error recovery heuristics performed by the compiler when running in procedural macro context. It is not clear to me that this is a bad thing -- the compiler will correctly remember to fail the compilation down the line. If you believe otherwise, please follow up in rust-lang/rust.

#### Cargo.toml

```toml
[package]
name = "repro"
version = "0.0.0"
edition = "2018"

[lib]
proc-macro = true
```

#### src/lib.rs

```rust
extern crate proc_macro;

use proc_macro::TokenStream;
use std::str::FromStr;

#[proc_macro_derive(ParseTokenStream)]
pub fn derive(_input: TokenStream) -> TokenStream {
    println!("{:#?}", TokenStream::from_str("Foo::Bar { elem"));
    TokenStream::new()
}
```

#### src/main.rs

```rust
#[derive(repro::ParseTokenStream)]
struct S;

fn main() {}
```

Output of `cargo check`:

```console
$ cargo check
   Compiling repro v0.0.0 (/media/david/coding/github/repro/repro)
error: this file contains an un-closed delimiter
 --> src/main.rs:1:10
  |
1 | #[derive(repro::ParseTokenStream)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^ un-closed delimiter

Ok(
    TokenStream [
        Ident {
            ident: "Foo",
            span: #4 bytes(9..32)
        },
        Punct {
            ch: ':',
            spacing: Joint,
            span: #4 bytes(9..32)
        },
        Punct {
            ch: ':',
            spacing: Alone,
            span: #4 bytes(9..32)
        },
        Ident {
            ident: "Bar",
            span: #4 bytes(9..32)
        },
        Group {
            delimiter: Brace,
            stream: TokenStream [
                Ident {
                    ident: "elem",
                    span: #4 bytes(9..32)
                }
            ],
            span: #4 bytes(9..32)
        }
    ]
)
error: aborting due to previous error

error: Could not compile `repro`.

To learn more, run the command again with --verbose.
```

**Comment by canndrew** [comment] 2019-02-27 08:27
Thanks! I've followed up here: https://github.com/rust-lang/rust/issues/58772. It would certainly be nice if I had the option to check for errors myself.
