### ISSUE TITLE
[Feature request] Make bracket / parenthesis parsing functions part of the public API

### ISSUE THREAD

**Issue by AaronErhardt** [dtolnay/syn#1190] opened 2022-06-19 12:09 UTC
The parsing functions used by macros like `parenthesized!` live in the `__private` module as internal undocumented publicly accessible code.

This brings several issues with it: Changes in these modules aren't considered a major change that requires a major version bump but some crates have no other choice but to use those functions because the macros don't work in all scenarios.

Besides, there are many other reasons to use those functions directly rather than through their corresponding macros (see https://github.com/dtolnay/syn/issues/1189).

> P. S. I really don't want to be annoying with these issues. You're doing a great job with this crate in general :)

**Comment by dtolnay** [comment] 2022-06-19 15:27
This is a duplicate of #1172.

I definitely don't agree with _"some crates have no other choice but to use those functions"_. You can easily wrap any of the syn macros in whatever signature is convenient for your use case.

**Closed by dtolnay** 2022-06-19 15:27 UTC

**Comment by AaronErhardt** [comment] 2022-06-19 15:51
I definitely don't want to bother you, but I just don't understand the reasoning. We already have an API that is better than the macros in every situation (more readable, less code, higher flexibility), so why can't we document it and make it public? I would send a PR for that.

You're right, it's just a bunch of lines to write a wrapper around the macro to get basically the same function that the macro uses internally, but why do I need to do this in the first place?
