### ISSUE TITLE
Broken doc link

### ISSUE THREAD

**Issue by Luro02** [dtolnay/syn#728] opened 2019-12-04 14:02 UTC
The link to `TokenStream` in https://docs.rs/syn/1.0.11/syn/enum.Type.html is broken.
This is the link: https://docs.rs/proc-macro2/1.0.6/proc_macro2/struct.TokenStream.html

**Comment by mystor** [comment] 2019-12-04 16:07
I believe this is caused by docs.rs erroring while building docs for `proc-macro2` (https://github.com/alexcrichton/proc-macro2/issues/203, https://github.com/rust-lang/docs.rs/issues/440).

**Comment by taiki-e** [comment] 2020-05-21 18:22
Seems to have already fixed in the latest documents: https://docs.rs/syn/1.0.23/syn/enum.Type.html

**Closed** 2020-05-21 18:29 UTC
