### ISSUE TITLE
Feature Request: An equivalent of braced!, parenthesized!, or bracketed! but for || to parse closure parameters and <> to parse generic types.

### ISSUE THREAD

**Issue by recatek** [dtolnay/syn#1384] opened 2023-02-26 05:08 UTC
It would be nice to have an equivalent of the braced!, parenthesized!, or bracketed! macros for parsing closure parameters denoted with || and generic types denoted with <>. I actually just ran into both of them at once for trying to parse closure arguments.

**Comment by dtolnay** [comment] 2023-02-26 05:23
Duplicate of #555.

**Closed by dtolnay** 2023-02-26 05:23 UTC

**Comment by recatek** [comment] 2023-02-26 06:15
Wanted to add a comment to that issue but it doesn't look like I can. I think in simple cases (that HTML case is pretty complicated), these macros would still be useful. Closure arguments can't have any intermediate | characters, I don't think. Generic types could, but in the same way that braces could be of the form [[]] and count to avoid stopping on the first close.
