### ISSUE TITLE
Parsing a MetaListNameValueStr

### ISSUE THREAD

**Issue by CraftSpider** [dtolnay/syn#873] opened 2020-07-24 03:37 UTC
There doesn't seem to be many built-in structs that supports parsing the `attr` value of an attribute macro. A MetaList expects parenthesis at the start of the token stream, which are stripped by the internals of the attribute macro system. The closest is a MetaNameValue, which can support a single argument, but not more than one.

**Comment by CraftSpider** [comment] 2020-12-16 23:29
The AttributeArgs type seems to be what I want, but I can't use `parse_macro_input!` with proc_macro2, and it doesn't implement `Parse` and thus I can't just use `syn::parse2` on it. Is there any alternative that doesn't involve copying its definition into my code and writing my own parse implementation?

**Comment by dtolnay** [comment] 2021-03-29 03:54
Closing as a duplicate of #616.

**Closed by dtolnay** 2021-03-29 03:54 UTC
